function buildSets() {
  const today = new Date();
  const todayStr = today.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const wrongDate = "15 January 2026";
  const weekdayDate = "15 September 2026"; // Tuesday

  return [
    [
      { instruction: "Press the bell to begin your prayer.", visual: "bell", action: "press", fail: "The bell was meant to be pressed." },
      { instruction: "Press ONLY if you see a Modak.", visual: "laddu", action: "no-press", fail: "That was a laddu, not a modak." },
      { instruction: "Remember this: there are 5 diyas lit.", visual: "diyas-5", action: "auto", fail: "" },
      { instruction: "Press if you remembered the number of diyas.", visual: "question", action: "press", fail: "Bappa only asked if you remembered — pressing was devotion enough." },
      { instruction: "Do NOT press until the conch sounds.", visual: "conch", action: "wait-press", cue: "conch", waitMs: 3000, fail: "The conch had not yet called." },
      { instruction: "Press if Ganesha's trunk curves left.", visual: "ganesha-trunk-right", action: "no-press", fail: "The trunk curved to the right." },
      { instruction: "Tap the Mushak — not the Modak.", visual: "mushak-modak", action: "tap", correct: "mushak", fail: "Mushak is Bappa's vahana. The modak was a decoy." },
      { instruction: "You Win! Continue to Aarti →", visual: "fake-win", action: "no-press", fail: "Aarti comes later. That victory was a trick." },
      { instruction: "Press if this rangoli pattern is symmetrical.", visual: "rangoli-asym", action: "no-press", fail: "One petal was smaller. Look twice." },
      { instruction: "Everyone presses this one. Are you sure?", visual: "crowd", action: "press", fail: "The crowd was right, for once." },
      { instruction: "Press if this is Ganesh Chaturthi's correct date.", visual: "date-wrong", action: "no-press", fail: `Chaturthi is not ${wrongDate}.` },
      { instruction: "Press to offer durva grass.", visual: "durva-full", action: "press", fail: "Durva is a beloved offering. Press to give it." },
      { instruction: " ", visual: "dim", action: "press", tiny: "press when ready", timeout: 10000, fail: "The tiny words in the corner were the real instruction." },
      { instruction: "Press if the aarti thali has a coconut on it.", visual: "thali-no-coconut", action: "no-press", fail: "No coconut on that thali." },
      { instruction: "Do NOT press if you hear the dhol beat.", visual: "dhol-play", action: "no-press", cue: "dhol-loop", fail: "The dhol was playing. Stillness was the prayer." },
      { instruction: "Press the modak that is slightly bigger.", visual: "modaks-left-big", action: "tap", correct: "left", fail: "The left modak was larger." },
      { instruction: "Press if Ganesha is smiling in this image.", visual: "ganesha-neutral", action: "no-press", fail: "Bappa's expression was calm, not a smile." },
      { instruction: "Last trial: press only when the bell stops ringing.", visual: "bell-ring", action: "wait-press", cue: "bell-stop", waitMs: 4000, fail: "Wait for the ringing to end." },
      { instruction: "The pandal doors are opening... press to enter.", visual: "doors", action: "press", fail: "The doors were open for you." },
      { instruction: "गणपती बाप्पा मोरया — You have received Bappa's blessing!", visual: "blessing", action: "win", winText: "You have received Bappa's blessing!" },
    ],
    [
      { instruction: "Press the diya to light your path.", visual: "diya-unlit", action: "press", fail: "Lighting the diya begins the path." },
      { instruction: "Press ONLY if you see a Modak.", visual: "peda", action: "no-press", fail: "That was a peda, not a modak." },
      { instruction: "Remember this: the flag has 3 colours.", visual: "flag", action: "auto", fail: "" },
      { instruction: "Press if you remembered the flag's colours.", visual: "question", action: "press", fail: "Pressing was enough. Memory was the joke." },
      { instruction: "Do NOT press until the aarti bell rings.", visual: "handbell", action: "wait-press", cue: "handbell", waitMs: 3500, fail: "Wait for the aarti bell." },
      { instruction: "Press if Ganesha's ears are the same size.", visual: "ganesha-ears", action: "no-press", fail: "One ear was larger." },
      { instruction: "Tap the flower — not the coconut.", visual: "flower-coconut", action: "tap", correct: "flower", fail: "The flower was the offering." },
      { instruction: "Congratulations, Devotee! Claim your prize →", visual: "fake-prize", action: "no-press", fail: "No prize yet. That screen was a trap." },
      { instruction: "Press if this pattern of flowers is evenly spaced.", visual: "flowers-gap", action: "no-press", fail: "One gap was uneven." },
      { instruction: "This one's obvious. Trust your instinct.", visual: "plain", action: "press", fail: "Instinct said press. It was safe." },
      { instruction: "Press if today matches the date shown on the banner.", visual: "date-mismatch", action: "no-press", fail: `Today is ${todayStr}, not the banner.` },
      { instruction: "Press to ring the small hand bell.", visual: "handbell", action: "press", fail: "A small ring was asked of you." },
      { instruction: "Wait for the scene to appear, then press.", visual: "fade", action: "press", timeout: 10000, fail: "Patience, then press." },
      { instruction: "Press if the puja thali has kumkum on it.", visual: "thali-no-kumkum", action: "no-press", fail: "The kumkum was missing." },
      { instruction: "Do NOT press while the procession music is playing.", visual: "music", action: "no-press", cue: "dhol-loop", fail: "Music was still playing." },
      { instruction: "Press the diya with the taller flame.", visual: "diyas-right-tall", action: "tap", correct: "right", fail: "The right flame was taller." },
      { instruction: "Press if Ganesha's eyes are open.", visual: "ganesha-closed", action: "no-press", fail: "Bappa was meditating, eyes closed." },
      { instruction: "Final trial: press the instant the conch stops sounding.", visual: "conch", action: "wait-press", cue: "conch-stop", waitMs: 4500, fail: "Press after the conch falls silent." },
      { instruction: "The curtain is lifting for darshan... press when ready.", visual: "curtain", action: "press", fail: "Darshan was waiting." },
      { instruction: "गणपती बाप्पा मोरया — Bappa has accepted your devotion!", visual: "blessing", action: "win", winText: "Bappa has accepted your devotion!" },
    ],
    [
      { instruction: "Press to fold your hands in prayer.", visual: "hands", action: "press", fail: "Namaskar begins with a press." },
      { instruction: "Press ONLY if you see a real Modak (not a drawing of one).", visual: "modak-sketch", action: "no-press", fail: "It was only a drawing." },
      { instruction: "Remember this: the rangoli has 6 petals.", visual: "rangoli-6", action: "auto", fail: "" },
      { instruction: "Press if you remembered the petal count.", visual: "question", action: "press", fail: "The memory check was kind. Pressing was correct." },
      { instruction: "Do NOT press until the drummers start.", visual: "dhol", action: "wait-press", cue: "dhol", waitMs: 3000, fail: "Wait for the drums." },
      { instruction: "Press if there are more diyas on the left than the right.", visual: "diyas-equal", action: "no-press", fail: "Both sides were equal." },
      { instruction: "Tap the bell — not the drum.", visual: "bell-drum", action: "tap", correct: "bell", fail: "The bell was the true target." },
      { instruction: "Trial Complete! Skip ahead to blessing →", visual: "fake-skip", action: "no-press", fail: "There is no skip. Blessing is earned." },
      { instruction: "Press if the marigold garland has an even number of flowers.", visual: "garland-odd", action: "no-press", fail: "There were 5 flowers — odd." },
      { instruction: "This is the hardest one. Take your time.", visual: "plain", action: "press", fail: "Intimidation only. A simple press was enough." },
      { instruction: "Press if the calendar shown is for this year.", visual: "calendar-wrong", action: "no-press", fail: "That calendar was last year's." },
      { instruction: "Press to place a flower at Bappa's feet.", visual: "flower-full", action: "press", fail: "Offer the flower." },
      { instruction: "uoᴉʇɔnɹʇsuᴉ ǝɥʇ pɐǝɹ", visual: "plain", action: "press", extra: "upside", tiny: "press to continue", fail: "The tiny upright line told you to press." },
      { instruction: "Press if the prasad plate has fruit on it.", visual: "thali-sweets", action: "no-press", fail: "Only sweets, no fruit." },
      { instruction: "Do NOT press if the temple bell is currently ringing.", visual: "bell-still", action: "press", fail: "The bell was silent, so pressing was safe." },
      { instruction: "Press the flower that is a different colour from the rest.", visual: "odd-flower", action: "tap", correct: "odd", fail: "The green flower was the odd one." },
      { instruction: "Press if Ganesha is facing forward.", visual: "ganesha-profile", action: "no-press", fail: "That was a side profile." },
      { instruction: "Final trial: press only after the second conch call.", visual: "conch", action: "wait-press", cue: "conch-twice", waitMs: 2800, fail: "Wait for the second call." },
      { instruction: "The aarti thali is being lifted... press to join in.", visual: "thali-full", action: "press", fail: "Join the aarti." },
      { instruction: "गणपती बाप्पा मोरया — Your devotion has reached Bappa!", visual: "blessing", action: "win", winText: "Your devotion has reached Bappa!" },
    ],
    [
      { instruction: "Press to greet Bappa with folded hands.", visual: "hands", action: "press", fail: "Greet with a press." },
      { instruction: "Press ONLY if you see two Modaks.", visual: "one-modak", action: "no-press", fail: "Only one modak was offered." },
      { instruction: "Remember this: the diya flame is orange, not yellow.", visual: "diya-orange", action: "auto", fail: "" },
      { instruction: "Press if you remembered the flame's colour.", visual: "question", action: "press", fail: "A kind check. Pressing was correct." },
      { instruction: "Do NOT press until the second bell chime.", visual: "bell", action: "wait-press", cue: "bell-twice", waitMs: 2200, fail: "The second chime had not yet come." },
      { instruction: "Press if Ganesha's crown has a jewel in the centre.", visual: "ganesha-jewel", action: "no-press", fail: "The jewel sat off-centre." },
      { instruction: "Tap the durva grass — not the marigold.", visual: "durva-marigold", action: "tap", correct: "durva", fail: "Durva is the sacred grass." },
      { instruction: "Blessing Received! Tap to exit →", visual: "fake-exit", action: "no-press", fail: "Do not exit early. That blessing was false." },
      { instruction: "Press if the diya row has a diya missing.", visual: "diyas-complete", action: "no-press", fail: "Every diya was present." },
      { instruction: "Don't overthink this one.", visual: "plain", action: "press", fail: "Overthinking failed you. Just press." },
      { instruction: "Press if the shown date falls on a Sunday.", visual: "date-weekday", extraText: weekdayDate, action: "no-press", fail: "15 September 2026 is a Tuesday." },
      { instruction: "Press to sprinkle rose petals.", visual: "petals", action: "press", fail: "Sprinkle with a press." },
      { instruction: "Press the button once it settles.", visual: "plain", action: "press", shift: true, timeout: 10000, fail: "Press the button in its final place." },
      { instruction: "Press if the prasad plate has a banana on it.", visual: "thali-apple", action: "no-press", fail: "That was an apple, not a banana." },
      { instruction: "Do NOT press if more than one instrument is playing.", visual: "dhol-bell", action: "no-press", cue: "both", fail: "Drum and bell played together." },
      { instruction: "Press the rangoli with more colours.", visual: "rangoli-compare", action: "tap", correct: "right", fail: "The right rangoli had more petals/colours." },
      { instruction: "Press if Ganesha's trunk touches the modak bowl.", visual: "ganesha-bowl", action: "no-press", fail: "The trunk did not touch the bowl." },
      { instruction: "Final trial: press only when both diyas are lit at the same time.", visual: "diyas-async", action: "wait-press", cue: "overlap", waitMs: 2400, fail: "Press only during the overlap." },
      { instruction: "The devotees are gathering for the final aarti... press to join.", visual: "crowd", action: "press", fail: "Join the gathering." },
      { instruction: "गणपती बाप्पा मोरया — Bappa welcomes you with open arms!", visual: "blessing", action: "win", winText: "Bappa welcomes you with open arms!" },
    ],
  ];
}
