/* === Image Asset Map — maps visual keys to background images === */
const ASSET_MAP = {
  bell:              'assets/temple_bell.jpg',
  'bell-ring':       'assets/temple_bell.jpg',
  'bell-still':      'assets/temple_bell.jpg',
  laddu:             'assets/modak_sweet.jpg',
  peda:              'assets/modak_sweet.jpg',
  'modak-sketch':    'assets/modak_sweet.jpg',
  'one-modak':       'assets/modak_sweet.jpg',
  'diyas-5':         'assets/lit_diyas.jpg',
  'diya-unlit':      'assets/lit_diyas.jpg',
  'diya-orange':     'assets/lit_diyas.jpg',
  'diyas-equal':     'assets/lit_diyas.jpg',
  'diyas-complete':  'assets/lit_diyas.jpg',
  'diyas-right-tall':'assets/lit_diyas.jpg',
  'diyas-async':     'assets/lit_diyas.jpg',
  conch:             'assets/pandal_entrance.jpg',
  'mushak-modak':    'assets/mushak_vahana.jpg',
  'modaks-left-big': 'assets/modak_sweet.jpg',
  'durva-full':      'assets/durva_grass.jpg',
  'durva-marigold':  'assets/durva_grass.jpg',
  'rangoli-asym':    'assets/ganesh_rangoli.jpg',
  'rangoli-6':       'assets/ganesh_rangoli.jpg',
  'rangoli-compare': 'assets/ganesh_rangoli.jpg',
  crowd:             'assets/visarjan_procession.jpg',
  'thali-no-coconut':'assets/puja_thali.jpg',
  'thali-no-kumkum': 'assets/puja_thali.jpg',
  'thali-sweets':    'assets/puja_thali.jpg',
  'thali-apple':     'assets/puja_thali.jpg',
  'thali-full':      'assets/puja_thali.jpg',
  doors:             'assets/pandal_entrance.jpg',
  curtain:           'assets/pandal_entrance.jpg',
  blessing:          'assets/ganesh_main_idol.jpg',
  'flower-coconut':  'assets/durva_grass.jpg',
  'flower-full':     'assets/durva_grass.jpg',
  'flowers-gap':     'assets/ganesh_rangoli.jpg',
  'garland-odd':     'assets/ganesh_rangoli.jpg',
  'odd-flower':      'assets/ganesh_rangoli.jpg',
  handbell:          'assets/temple_bell.jpg',
  flag:              'assets/pandal_entrance.jpg',
  hands:             'assets/ganesh_main_idol.jpg',
  petals:            'assets/ganesh_rangoli.jpg',
  'dhol-play':       'assets/visarjan_procession.jpg',
  dhol:              'assets/visarjan_procession.jpg',
  'dhol-bell':       'assets/visarjan_procession.jpg',
  'bell-drum':       'assets/temple_bell.jpg',
  music:             'assets/visarjan_procession.jpg',
  'ganesha-trunk-right': 'assets/ganesh_main_idol.jpg',
  'ganesha-neutral':     'assets/ganesh_main_idol.jpg',
  'ganesha-ears':        'assets/ganesh_main_idol.jpg',
  'ganesha-closed':      'assets/ganesh_main_idol.jpg',
  'ganesha-profile':     'assets/ganesh_main_idol.jpg',
  'ganesha-jewel':       'assets/ganesh_main_idol.jpg',
  'ganesha-bowl':        'assets/ganesh_main_idol.jpg',
  question:              'assets/ganesh_rangoli.jpg',
  'date-wrong':          'assets/pandal_entrance.jpg',
  'date-mismatch':       'assets/pandal_entrance.jpg',
  'date-weekday':        'assets/pandal_entrance.jpg',
  'calendar-wrong':      'assets/pandal_entrance.jpg',
};

/* === Preload all unique asset images on page load === */
const _preloadCache = {};
(function preloadAssets() {
  const urls = [...new Set(Object.values(ASSET_MAP))];
  urls.forEach(url => {
    const img = new Image();
    img.src = url;
    _preloadCache[url] = img;
  });
})();

function getTrialBg(visualKey) {
  return ASSET_MAP[visualKey] || null;
}

function buildSets() {
  const today = new Date();
  const todayStr = today.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const wrongDate = "15 January 2026";
  const weekdayDate = "15 September 2026"; // Tuesday

  return [
    [
      { instruction: "Press the bell — Ganesh was created by Goddess Parvati from sandalwood paste.", visual: "bell", action: "press", fail: "The bell was meant to be pressed. Parvati's creation awaits." },
      { instruction: "Press ONLY if you see a Modak — Ganesh's most beloved sweet.", visual: "laddu", action: "no-press", fail: "That was a laddu, not a modak. Ganesh knows the difference!" },
      { instruction: "Remember this: Ganesh has 4 arms (Chaturbhuj). How many diyas are lit? 5.", visual: "diyas-5", action: "auto", fail: "" },
      { instruction: "Ganesh is called Buddhipriya (lover of wisdom). Press if you remembered the diya count.", visual: "question", action: "press", fail: "Buddhipriya only asked if you remembered — pressing was devotion enough." },
      { instruction: "Do NOT press until the shankh (conch) sounds — it signals the start of Ganesh puja.", visual: "conch", action: "wait-press", cue: "conch", waitMs: 3000, fail: "The shankh had not yet called. Wait for Ganesh's signal." },
      { instruction: "Press if Ganesh's trunk curves LEFT. A left trunk (Vaamamukhi) means a calm, gentle Ganesh.", visual: "ganesha-trunk-right", action: "no-press", fail: "The trunk curved right — this is Siddhi Vinayak, the powerful form." },
      { instruction: "Tap Mushak — Ganesh's mouse who carries the Lord of the Universe! Not the Modak.", visual: "mushak-modak", action: "tap", correct: "mushak", fail: "Mushak symbolises ego controlled by wisdom. He was the target." },
      { instruction: "You Win! Ganesh has blessed you →", visual: "fake-win", action: "no-press", fail: "Ganesh tests patience, not haste. That victory was a trick." },
      { instruction: "Press if this Chaturthi rangoli is symmetrical — Ganesh loves perfection (Siddhi).", visual: "rangoli-asym", action: "no-press", fail: "One petal was smaller. Siddhi means perfection — look twice." },
      { instruction: "Ganesh broke his own tusk to write the Mahabharata. Press if you trust the crowd.", visual: "crowd", action: "press", fail: "The crowd was right, for once. Ekadanta wrote with his broken tusk." },
      { instruction: "Press if this is Ganesh Chaturthi's date — the Shukla Chaturthi of Bhadrapada.", visual: "date-wrong", action: "no-press", fail: `Chaturthi falls in Bhadrapada month, not ${wrongDate}.` },
      { instruction: "Ganesh loves Durva grass in bundles of 21. Press to offer Durva to Bappa.", visual: "durva-full", action: "press", fail: "21 blades of Durva is a sacred offering. Press to give it." },
      { instruction: "Ganesh is also called Vakratunda (curved trunk).", visual: "dim", action: "press", tiny: "press when ready", timeout: 10000, fail: "Vakratunda's tiny words in the corner were the real instruction." },
      { instruction: "Press if the thali has a coconut — Ganesh's favourite fruit (Shreephala).", visual: "thali-no-coconut", action: "no-press", fail: "No Shreephala (coconut) on that thali." },
      { instruction: "Do NOT press if the dhol plays — Ganesh as Nritya Ganapati wants stillness now.", visual: "dhol-play", action: "no-press", cue: "dhol-loop", fail: "The dhol was playing. Nritya Ganapati required stillness." },
      { instruction: "Ganesh is Modakapriya (lover of modaks). Tap the BIGGER modak for him!", visual: "modaks-left-big", action: "tap", correct: "left", fail: "Modakapriya deserves the biggest — the left modak was larger." },
      { instruction: "Press if Ganesh shows his Prasanna (joyful) form — is he smiling?", visual: "ganesha-neutral", action: "no-press", fail: "Bappa's expression was calm, not Prasanna (joyful)." },
      { instruction: "Ganesh rides Mushak slowly. Press only when the aarti bell STOPS ringing.", visual: "bell-ring", action: "wait-press", cue: "bell-stop", waitMs: 4000, fail: "Wait for the ringing to end. Mushak teaches patience." },
      { instruction: "The pandal doors open — Ganesh Chaturthi Sthapana (installation) begins! Press to enter.", visual: "doors", action: "press", fail: "The Sthapana doors were open for you." },
      { instruction: "गणपती बाप्पा मोरया — Ekadanta has blessed you!", visual: "blessing", action: "win", winText: "Ekadanta has blessed you!" },
    ],
    [
      { instruction: "Press the diya — Ganesh is Vighnaharta, remover of all obstacles. Light the way!", visual: "diya-unlit", action: "press", fail: "Vighnaharta's diya was meant to be lit." },
      { instruction: "Press ONLY if you see a Modak — NOT a Peda. Ganesh can tell the difference!", visual: "peda", action: "no-press", fail: "That was a peda. Buddhidata (giver of wisdom) won't be fooled." },
      { instruction: "Remember: Ganesh's father Shiva gave him the title 'Ganapati' — leader of the Ganas. The flag has 3 colours.", visual: "flag", action: "auto", fail: "" },
      { instruction: "Ganesh is Prathamapujya — always worshipped first. Press if you remembered the flag.", visual: "question", action: "press", fail: "Prathamapujya says pressing was enough. Memory was the joke." },
      { instruction: "Do NOT press until the aarti bell rings — Heramba (Ganesh) protects the devoted.", visual: "handbell", action: "wait-press", cue: "handbell", waitMs: 3500, fail: "Heramba hadn't rung the bell yet. Wait for protection." },
      { instruction: "Press if Ganesh's large ears (Gajakarna — elephant ears) are the same size.", visual: "ganesha-ears", action: "no-press", fail: "Gajakarna's ears were uneven — 'listen more, speak less.'" },
      { instruction: "Tap the flower — Ganesh loves red Jaswand (hibiscus). Not the coconut!", visual: "flower-coconut", action: "tap", correct: "flower", fail: "Red Jaswand (hibiscus) was the correct offering." },
      { instruction: "Congratulations! Claim your Ganesh idol prize →", visual: "fake-prize", action: "no-press", fail: "Ganesh teaches Viveka (discernment). That prize was a trap." },
      { instruction: "Press if this garland for Shri Ganesh is evenly spaced — perfection matters.", visual: "flowers-gap", action: "no-press", fail: "One gap was uneven. Offerings to Ganesh must be perfect." },
      { instruction: "Ganesh has 108 names. This one's obvious — Sumukha (beautiful face). Trust instinct.", visual: "plain", action: "press", fail: "Sumukha said press. Instinct was safe." },
      { instruction: "Press if the Chaturthi banner date matches today — Ganesh values Satya (truth).", visual: "date-mismatch", action: "no-press", fail: `Today is ${todayStr}. Satya (truth) means checking dates.` },
      { instruction: "Press to ring the bell — Ganesh is Dvaimatura (son of two mothers, Parvati & Ganga).", visual: "handbell", action: "press", fail: "Dvaimatura's bell was asking for a small ring." },
      { instruction: "Ganesh wrote the entire Mahabharata non-stop. Wait patiently, then press.", visual: "fade", action: "press", timeout: 10000, fail: "Patience, like Ganesh writing the Mahabharata, then press." },
      { instruction: "Press if the puja thali has kumkum — Ganesh's forehead is marked with Sindoor.", visual: "thali-no-kumkum", action: "no-press", fail: "The Sindoor (kumkum) was missing from the thali." },
      { instruction: "Ganesh is Vinayaka (supreme leader). Do NOT press while Visarjan music plays.", visual: "music", action: "no-press", cue: "dhol-loop", fail: "Vinayaka's procession music was still playing." },
      { instruction: "Tap the diya with the TALLER flame — a brighter offering pleases Lambodara.", visual: "diyas-right-tall", action: "tap", correct: "right", fail: "Lambodara (big belly = universe) prefers the taller right flame." },
      { instruction: "Press if Ganesha's eyes are OPEN — Ganesh sees all with Divya Drishti.", visual: "ganesha-closed", action: "no-press", fail: "Bappa was in dhyana (meditation), eyes closed. No Divya Drishti." },
      { instruction: "Ganesh's tusk is called Ekadanta. Press the INSTANT the conch stops sounding.", visual: "conch", action: "wait-press", cue: "conch-stop", waitMs: 4500, fail: "Press after the conch falls silent. Ekadanta awaits." },
      { instruction: "The curtain lifts — Ganesh Darshan (divine viewing) begins. Press when ready.", visual: "curtain", action: "press", fail: "Darshan (divine viewing) was waiting." },
      { instruction: "गणपती बाप्पा मोरया — Vighnarajaya Namah! Bappa accepts your devotion!", visual: "blessing", action: "win", winText: "Vighnarajaya Namah! Bappa accepts your devotion!" },
    ],
    [
      { instruction: "Press to fold hands — say 'Om Gan Ganapataye Namah' before Ganapati.", visual: "hands", action: "press", fail: "Om Gan Ganapataye Namah — Namaskar begins with a press." },
      { instruction: "Ganesh once ate so many modaks his belly burst! Press ONLY if you see a REAL modak.", visual: "modak-sketch", action: "no-press", fail: "It was only a drawing. Ganesh's belly burst from real modaks!" },
      { instruction: "Ganesh raced around his parents instead of the world and WON. Rangoli has 6 petals. Remember.", visual: "rangoli-6", action: "auto", fail: "" },
      { instruction: "Ganesh's wisdom beat Kartikeya's speed. Press if you remembered the petal count.", visual: "question", action: "press", fail: "Like Ganesh beating Kartikeya — wisdom wins. Pressing was correct." },
      { instruction: "Lord Shiva cut Ganesh's head — then gave him an elephant head. Wait for the dhol.", visual: "dhol", action: "wait-press", cue: "dhol", waitMs: 3000, fail: "Wait for the drums, like Shiva waited to find the elephant." },
      { instruction: "Press if there are MORE diyas on LEFT — Ganesh teaches equal vision (Samadarshi).", visual: "diyas-equal", action: "no-press", fail: "Samadarshi (equal vision) — both sides were equal." },
      { instruction: "Tap the BELL, not the drum — Ganesh hears prayers through gentle sounds.", visual: "bell-drum", action: "tap", correct: "bell", fail: "The bell was the true puja instrument." },
      { instruction: "Trial Complete! Skip to Ganesh's blessing →", visual: "fake-skip", action: "no-press", fail: "Chaturthi lasts up to 10 days — no shortcuts to blessing!" },
      { instruction: "Press if the marigold garland has an EVEN number — Ganesh prefers pairs.", visual: "garland-odd", action: "no-press", fail: "There were 5 flowers — odd. Ganesh noticed." },
      { instruction: "Ganesh defeated the demon Analasura by swallowing him! This trial is easy — press.", visual: "plain", action: "press", fail: "Like Analasura, intimidation only. A simple press was enough." },
      { instruction: "Press if this calendar shows THIS year's Bhadrapada — the month of Ganesh Chaturthi.", visual: "calendar-wrong", action: "no-press", fail: "That calendar was last year's. Bhadrapada is Aug-Sep." },
      { instruction: "Press to offer red Jaswand (hibiscus) — it represents Ganesh's Shakti (power).", visual: "flower-full", action: "press", fail: "Jaswand (hibiscus) is Ganesh's flower. Offer it." },
      { instruction: "Ganesh is Vighneshwara — lord of obstacles.", visual: "plain", action: "press", extra: "upside", tiny: "press to continue", fail: "Vighneshwara's tiny upright line told you to press." },
      { instruction: "Press if the prasad plate has fruit — Ganesh's belly (Mahodara) holds everything!", visual: "thali-sweets", action: "no-press", fail: "Only sweets, no fruit. Mahodara noticed." },
      { instruction: "Do NOT press if the temple bell is currently ringing. Ganesh as Dhumravarna meditates.", visual: "bell-still", action: "press", fail: "Dhumravarna's bell was silent. Pressing was safe." },
      { instruction: "Ganesh spots every detail (Sarvadevatman). Tap the ODD-coloured flower!", visual: "odd-flower", action: "tap", correct: "odd", fail: "Sarvadevatman sees all — the odd flower was the target." },
      { instruction: "Press if Ganesh faces FORWARD (Abhimukha). He is Kapila (tawny-coloured).", visual: "ganesha-profile", action: "no-press", fail: "Kapila was in profile — not Abhimukha (forward-facing)." },
      { instruction: "Ganesh told Vyasa: 'Don't pause or I stop writing.' Press after the 2nd conch.", visual: "conch", action: "wait-press", cue: "conch-twice", waitMs: 2800, fail: "Wait for the second call, like Vyasa waited for Ganesh." },
      { instruction: "The aarti thali lifts — Ganesh Utsav (festival) reaches its peak! Press to join.", visual: "thali-full", action: "press", fail: "Join the Ganesh Utsav aarti." },
      { instruction: "गणपती बाप्पा मोरया — Vighneshwara has embraced your devotion!", visual: "blessing", action: "win", winText: "Vighneshwara has embraced your devotion!" },
    ],
    [
      { instruction: "Press to greet Lambodara — his big belly holds the entire cosmos (Brahmanda).", visual: "hands", action: "press", fail: "Lambodara's Brahmanda (cosmos) awaited your greeting." },
      { instruction: "Ganesh holds a Pasha (noose) and Ankusha (goad). Press ONLY if you see TWO modaks.", visual: "one-modak", action: "no-press", fail: "Pasha captures obstacles, but only one modak was offered." },
      { instruction: "Ganesh's broken tusk is called 'Ekadanta.' The diya flame is ORANGE. Remember this.", visual: "diya-orange", action: "auto", fail: "" },
      { instruction: "Ganesh holds an Axe (Parashu) to cut attachments. Press if you remembered the colour.", visual: "question", action: "press", fail: "Parashu cuts doubt. A kind check — pressing was correct." },
      { instruction: "Do NOT press until the 2nd bell — Ganesh's Ashta Vinayak has 8 temples, patience for each!", visual: "bell", action: "wait-press", cue: "bell-twice", waitMs: 2200, fail: "The second chime for Ashta Vinayak had not yet come." },
      { instruction: "Press if Ganesh's Mukut (crown) has a jewel in the CENTRE — his third eye is Trinetra.", visual: "ganesha-jewel", action: "no-press", fail: "Trinetra's jewel sat off-centre in the Mukut." },
      { instruction: "Tap Durva grass — Ganesh prefers it over flowers! Durva cooled Ganesh after swallowing Analasura.", visual: "durva-marigold", action: "tap", correct: "durva", fail: "Durva cooled Ganesh's belly after Analasura. It is the sacred grass." },
      { instruction: "Blessing Received! Exit Ganesh's pandal →", visual: "fake-exit", action: "no-press", fail: "Visarjan hasn't happened yet! Do not exit early." },
      { instruction: "Ganesh's Mushak once stole all the modaks! Press if a diya is MISSING from the row.", visual: "diyas-complete", action: "no-press", fail: "Every diya was present. Mushak was greedy, not the diyas." },
      { instruction: "Ganesh is Siddhi Vinayak — giver of success. Don't overthink, just press.", visual: "plain", action: "press", fail: "Siddhi Vinayak (giver of success) said: just press." },
      { instruction: "Press if the shown date falls on a Sunday — Ganesh's day is Chaturthi (4th lunar day).", visual: "date-weekday", extraText: weekdayDate, action: "no-press", fail: "15 September 2026 is a Tuesday. Sankashti Chaturthi is the 4th day." },
      { instruction: "Press to sprinkle petals — Ganesh's colour is Sindoori (vermilion red).", visual: "petals", action: "press", fail: "Sindoori (vermilion) petals — sprinkle with a press." },
      { instruction: "Ganesh is Sthapati (cosmic architect). Wait for the button to settle, then press.", visual: "plain", action: "press", shift: true, timeout: 10000, fail: "Sthapati builds with patience. Press the settled button." },
      { instruction: "Press if the plate has a Kadali (banana) — Ganesh loves Kadali Phala!", visual: "thali-apple", action: "no-press", fail: "That was an apple, not Kadali (banana). Ganesh noticed." },
      { instruction: "Ganesh's vehicle Mushak was once the demon Kroncha! Do NOT press if 2+ instruments play.", visual: "dhol-bell", action: "no-press", cue: "both", fail: "Kroncha (Mushak) heard drum and bell together. Don't press." },
      { instruction: "Ganesh appreciates Kolam (rangoli). Tap the rangoli with MORE colours!", visual: "rangoli-compare", action: "tap", correct: "right", fail: "The right Kolam had more colours for Ganesh." },
      { instruction: "Press if Ganesh's trunk touches the modak bowl — Ganesh as Bhalchandra wears the moon.", visual: "ganesha-bowl", action: "no-press", fail: "Bhalchandra's trunk did not touch the bowl." },
      { instruction: "Ganesh cursed the moon (Chandra) for laughing! Press when BOTH diyas are lit together.", visual: "diyas-async", action: "wait-press", cue: "overlap", waitMs: 2400, fail: "Like Chandra's timing — press only during the overlap." },
      { instruction: "Devotees chant 'Ganapati Bappa Morya, Purchya Varshi Laukarya!' Press to join Visarjan.", visual: "crowd", action: "press", fail: "Join the Visarjan — 'Come again early next year!'" },
      { instruction: "गणपती बाप्पा मोरया — पुढच्या वर्षी लवकर या! Bappa welcomes you!", visual: "blessing", action: "win", winText: "पुढच्या वर्षी लवकर या! Bappa welcomes you!" },
    ],
  ];
}
